# Generated by Django 2.2.1 on 2019-07-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('commentor', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Code')),
            ],
        ),
    ]
