# Generated by Django 2.2.1 on 2019-07-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.CharField(max_length=200)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Code')),
            ],
        ),
    ]
